### ISSUE TITLE
File comes in 7zip(7z) format

### ISSUE THREAD

**Issue by Exanoff12** [AKPR2007/W10-in-android_termux#2]
the boot image file comes in 7zip(7z) format. not a big deal but direct image file will be cool. i will fix it soon. also make image selection auto by using wget. have any good file sharing site with no expiration ? dont suggest mediafire or mega beacuse mediafire has 8m expiration and also not available in most countries. mega has a bad bandwidth limit.

**Comment by AKPR2007** [comment]
I think apkadmin will be a good site. Apk admin has no expiration date and also unlimited download bandwidth. It also has a direct link option.
